"""Domain contracts for multi-specimen inverse identification."""

from .evidence import (
    EvidenceProvenance,
    EvidenceRecord,
    EvidenceSourceIdentity,
    IdentificationEvidence,
    IdentifiabilityEvidence,
    SensitivityEvidence,
    ValidationEvidence,
    evidence_content_hash,
    evidence_from_dict,
    evidence_from_json,
)
from .identification_campaign import IdentificationCampaign
from .material_identification_session import (
    FixedParameterValue,
    MaterialIdentificationEvidenceReference,
    MaterialIdentificationSession,
    MaterialIdentificationSourceIdentities,
    MaterialIdentificationTaskDefinition,
    ParameterBounds,
    SessionReadiness,
    resolve_identification_model,
)
from .modal_observation import (
    InclusionStatus,
    ModalCluster,
    ModalObservation,
    ObservationUncertainty,
)
from .parameter_model import (
    IdentificationParameter,
    ParameterPrior,
    ParameterResultStatus,
    ParameterRole,
    ParameterScope,
)
from .registration import (
    FROZEN_REGISTRATION_SCHEMA,
    REGISTRATION_DOF_COMPONENTS,
    FrozenRegistration,
    RegistrationMismatchError,
)
from .identification_model import (
    EFFECTIVE_FACE_SHEET_MODEL,
    EFFECTIVE_FACE_SHEET_V2_MODEL,
    STAGE_A_BENDING_MODEL,
    IdentificationModelDefinition,
    IdentificationParameterDefinition,
    ModelWorkflowStatus,
)
from .specimen import (
    CoreFamily,
    Design,
    FaceSectionFamily,
    InterfaceFamily,
    PhysicalSpecimen,
    PrimaryMeasurement,
    TestRun,
)

__all__ = [
    "CoreFamily",
    "Design",
    "EFFECTIVE_FACE_SHEET_MODEL",
    "EFFECTIVE_FACE_SHEET_V2_MODEL",
    "IdentificationModelDefinition",
    "IdentificationParameterDefinition",
    "ModelWorkflowStatus",
    "STAGE_A_BENDING_MODEL",
    "EvidenceProvenance",
    "EvidenceRecord",
    "EvidenceSourceIdentity",
    "FaceSectionFamily",
    "FixedParameterValue",
    "FROZEN_REGISTRATION_SCHEMA",
    "FrozenRegistration",
    "IdentificationCampaign",
    "IdentificationEvidence",
    "IdentificationParameter",
    "IdentifiabilityEvidence",
    "InclusionStatus",
    "InterfaceFamily",
    "MaterialIdentificationEvidenceReference",
    "MaterialIdentificationSession",
    "MaterialIdentificationSourceIdentities",
    "MaterialIdentificationTaskDefinition",
    "ModalCluster",
    "ModalObservation",
    "ObservationUncertainty",
    "ParameterPrior",
    "ParameterBounds",
    "ParameterResultStatus",
    "ParameterRole",
    "ParameterScope",
    "PhysicalSpecimen",
    "PrimaryMeasurement",
    "REGISTRATION_DOF_COMPONENTS",
    "RegistrationMismatchError",
    "SensitivityEvidence",
    "SessionReadiness",
    "TestRun",
    "ValidationEvidence",
    "evidence_content_hash",
    "evidence_from_dict",
    "evidence_from_json",
    "resolve_identification_model",
]
